In [67]:
import numpy as np
from scipy import stats

with open('input.txt') as f:
    lines = f.read().splitlines()

In [19]:
arr = np.array([[int(c) for c in l] for l in lines])
mode = []
for col in range(len(arr[0])):
    mode.append(stats.mode(arr[:,col]).mode[0])
gamma = ''.join(map(str, mode))
epsilon = [int(not bool(int(c))) for c in gamma]
epsilon = ''.join(map(str, epsilon))
print(int(gamma, base=2) * int(epsilon, base=2))

In [68]:
# lines = '''00100
# 11110
# 10110
# 10111
# 10101
# 01111
# 00111
# 11100
# 10000
# 11001
# 00010
# 01010'''.splitlines()

array = np.array([[int(c) for c in l] for l in lines])

def read_sensor_values(type):
    arr = array.copy()
    for col in range(len(arr[0])):
        ones = np.count_nonzero(arr[:,col])
        zeros = len(arr) - ones
        if zeros > ones:
            mode = 0
        else:
            mode = 1
        if type == -1:
            mode = int(not bool(mode))
        selected = np.where(arr[:,col] == mode)
        arr = arr[selected]
        if len(arr) == 1:
            print(arr[0])
            return ''.join(map(str, arr[0]))

oxygen = int(read_sensor_values(1), base=2)
co2 = int(read_sensor_values(-1), base=2)
print(oxygen, co2, oxygen * co2)


[[0 1 1 ... 1 0 1]
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 1 0 1]
 ...
 [0 0 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 0 0 0]]
[[0 1 1 ... 1 0 1]
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 0 0 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 0 0 0]]
[[0 1 0 ... 0 1 1]
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 0 1 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 0 0 0]]
[[0 1 0 1 1 1 0 1 0 0 1 0]
 [0 1 0 1 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 0 0 1 0 1 1 1]
 [0 1 0 1 0 1 1 0 1 1 1 0]
 [0 1 0 1 0 0 1 1 0 0 1 1]
 [0 1 0 1 0 0 0 1 0 0 0 1]
 [0 1 0 1 1 1 1 0 1 1 0 0]
 [0 1 0 1 1 1 0 0 1 0 0 1]
 [0 1 0 1 0 1 1 0 1 1 0 0]
 [0 1 0 1 1 1 0 1 1 1 1 1]
 [0 1 0 1 1 0 0 0 1 1 0 1]
 [0 1 0 1 0 1 0 1 1 1 1 1]
 [0 1 0 1 1 1 0 0 1 1 1 0]
 [0 1 0 1 1 1 0 0 1 1 0 1]
 [0 1 0 1 0 0 1 1 0 1 1 1]
 [0 1 0 1 1 0 0 1 0 1 0 1]
 [0 1 0 1 0 0 1 0 1 0 1 0]
 [0 1 0 1 1 0 1 1 0 0 0 1]
 [0 1 0 1 1 1 1 0 0 0 0 1]
 [0 1 0 1 0 0 0 1 1 0 0 0]
 [0 1 0 1 1 1 0 1 0 1 0 1]
 [0 1 0 1 1 0 0 1 1 0 1 0]
 [0 1 0 1 1 1 1 1 0 1 1 0]
 [0 1 0 1 1 0 0 0 0